### ISSUE TITLE
I need explanations about BaseService methods

### ISSUE THREAD

**Issue by denisakp** [fless-lab/node-ts-starter#14]
Could you please give an understanding of the following methods in `BaseService` class ?

- ensureUniqueField
- ensureUniqueSlug
- ensureRequiredFields
- detectUniqueFields

**Comment by fless-lab** [comment]
Hey @denisakp ... Here is some explanation for each method

### `ensureUniqueField`

**Description:**
This method ensures that a particular field in a document is unique. Before saving or updating a document, it checks if the value of the specified field already exists in another document within the collection.

**How it works:**
- The method takes a document and a field as parameters.
- It searches the repository for any document with the same field value, excluding the current document (to handle updates).
- If a duplicate is found, it throws an error indicating that the field must be unique.

### `ensureUniqueSlug`

**Description:**
This method ensures that a slug field in a document is unique. Slugs are often used in URLs for SEO-friendly and human-readable identifiers.

**How it works:**
- It generates a slug from a specified input field (e.g., a name).
- It checks if any document in the repository already has the same slug.
- If a duplicate slug is found, it appends a counter to the slug (e.g., `example`, `example-1`, `example-2`, etc.) until a unique slug is found.
- It then assigns this unique slug to the document.

### `ensureRequiredFields`

**Description:**
This method ensures that all required fields are present in a document before it is saved or updated.

**How it works:**
- It inspects the schema of the model to determine which fields are marked as required.
- It checks if these required fields are present in the input document.
- If any required fields are missing, it throws an error listing the missing fields and suggesting that they be provided.

### `detectUniqueFields`

**Description:**
This method identifies all the fields in the model schema that are marked as unique.

**How it works:**
- It iterates over the schema paths of the model.
- For each path, it checks if the `unique` option is set.
- It compiles a list of these unique fields and returns it.

Each of these methods plays a crucial role in maintaining data integrity and consistency by enforcing uniqueness constraints and ensuring required fields are provided.



If you have some other question, don't hesitate

**Comment by denisakp** [comment]
Hey @fless-lab  thanks for your answer.

Isn't this the point of MongoDB indexes? I mean, you're already overriding properties in the model schema using the `SchemaTypeOptions` interface .

```typescript
const UserSchema: Schema = new Schema(
  {
    firstname: { type: String, required: true },
    lastname: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
    role: { type: String, enum: ['admin', 'user', 'guest'], default: 'user' },
    profilePhoto: { type: String },
  },
  { timestamps: true },
);
```

 This makes Mongo aware of the schema constraints, which are examined prior to any write operation (create, update, delete).  So, I'm confused because those methods looks like a form of redundancy as the ODM (mongoose) already take care of that.

In terms of performance, if we have one million documents, for instance, how much effort will those type of verification can cost in term of computational resources ? 

I'd like to point out that I'm only interested in the performance in a production environment, so I regard these checks as unnecessary and will increase the workload.

However, kindly correct me if I am mistaken.

**Comment by fless-lab** [comment]
Great points. And you're right when saying that MongoDB and Mongoose handle unique constraints and required fields at the database level using indexes and schema definitions. The methods in question might appear redundant at first glance because they replicate some of these responsibilities.

I've added these methods first in order to return user-friendly error messages instead of Mongo errors. Also, performing these checks before hitting the database can prevent unnecessary database operations, which can be beneficial in certain scenarios. For example, it allows us to avoid attempting to save a document that we know will fail due to a unique constraint, saving a round-trip to the database.

But you're right when saying that performing these checks adds overhead 😅, especially as the dataset grows. For a system with a million documents, this can indeed have a significant performance impact.

To address this concern, a flexible solution would be to make these checks optional. This way, you can enable or disable them based on your specific use case. Here's how we can do that:

- Introduce Configuration Options: Add configuration options to enable or disable each type of check.

- Modify Methods to Respect Configuration: Update the service methods to respect these configuration options.

For example, in the BaseService class, we can add configuration options and modify methods to conditionally perform checks:

```
export class BaseService<T extends Document, R extends BaseRepository<T>> {
  protected repository: R;
  protected handleSlug: boolean;
  protected uniqueFields: string[];
  protected populateFields: string[];
  protected allowedFilterFields?: string[];
  protected searchFields?: string[];
  protected config: {
    checkUniqueFields: boolean;
    checkRequiredFields: boolean;
  };
  
  // ...
 /* And at usage do something like */
  //...
  
  async create(
    input: Partial<T>,
  ): Promise<SuccessResponseType<T> | ErrorResponseType> {
    try {
      if (this.config.checkUniqueFields) {
        for (const field of this.uniqueFields) {
          await this.ensureUniqueField(input, field as keyof T);
        }
      }
      if (this.handleSlug) await this.ensureUniqueSlug(input);
      if (this.config.checkRequiredFields) {
        await this.ensureRequiredFields(input);
      }
      const document = await this.repository.create(input);
      return { success: true, document };
    } catch (error) {
      return {
        success: false,
        error:
          error instanceof ErrorResponse
            ? error
            : new ErrorResponse('DATABASE_ERROR', (error as Error).message),
      };
    }
  }

**Comment by fless-lab** [comment]
So to address these concerns, we could consider making these checks optional so that they can be enabled or disabled based on the specific needs and priorities of the project. This way, for development or smaller datasets, we can have more user-friendly error handling, and for production with large datasets, we can rely on the database constraints.

If you have any other suggestions or solutions to improve performance while maintaining the benefits of these checks, I'm all ears!

**Comment by denisakp** [comment]
> ```js
> async create(
>     input: Partial<T>,
>   ): Promise<SuccessResponseType<T> | ErrorResponseType> {
>     try {
>       if (this.config.checkUniqueFields) {
>         for (const field of this.uniqueFields) {
>           await this.ensureUniqueField(input, field as keyof T);
>         }
>       }
>       if (this.handleSlug) await this.ensureUniqueSlug(input);
>       if (this.config.checkRequiredFields) {
>         await this.ensureRequiredFields(input);
>       }
>       const document = await this.repository.create(input);
>       return { success: true, document };
>     } catch (error) {
>       return {
>         success: false,
>         error:
>           error instanceof ErrorResponse
>             ? error
>             : new ErrorResponse('DATABASE_ERROR', (error as Error).message),
>       };
>     }
> ```

Mongoose offers a useful Error [definition](https://mongoosejs.com/docs/api/error.html#Error.prototype.name) that can simplify your development life 😅

You've also created a great, expandable exception handler. So, in my opinion, you should create a mongoose exception handler similar to the one you used for the `notFoundHandler` and switch on the Mongoose Error Prototype Name. 

If we want to follow the Single Responsibility concept, the catch block should solely be responsible for propagating the exception across the program. 

```typescript
function myfunc () {
  try {
    console.log("Implement a nince stuff")
  }
  catch (error) {
    // is assume the project has a cool logging system
    // with tools such as winston, pinio, morgan .....
    console.error(error) 
    
    // propagate the error in the system by simply throwing it
    throw error
  }
}
```
This way, our method/function is simply concerned with processing logic. If an error occurs, it merely ensures that the error handlers are aware of it and will take the appropriate action. And, because this is a Node.Js project, we can write error middleware to capture any exceptions in the system and return the relevant well-formatted error response. 

```typescript
function myfunyController (res, res, next) {
  try {
    return res.json({"ping": "pong"})
  }
  catch (error) {
    next(error)
  }
}
```
When we pass an error to the next() function, we are passing it to Express, where the appropriate middleware will handle the remainder. More details [here](https://expressjs.com/en/guide/error-handling.html)

That's how i would process for the mongoose error handling using the provided stuffs

**Comment by fless-lab** [comment]
Yeah that's a good point...


This means that we will always hit the database before it returns the error..right ?

**Comment by denisakp** [comment]
> This means that we will always hit the database before it returns the error..right ?

Exactly 👍🏼

**Comment by fless-lab** [comment]
I wanted to trigger the error before db access..


Also if there are multiple unique constraints violated in a single operation, MongoDB (via Mongoose) typically reports only the first unique constraint violation it encounters. The error message will indicate the first field that failed the unique constraint check, not all of them..But i want to return all concerned things... Same for required constraints
